sudo: false
git:
  depth: 1
language: ruby
bundler_args: --without development testext production --deployment --jobs=4 --retry=5
cache: bundler

rvm:
  - jruby-9.1.5.0

matrix:
  include:
    - { rvm: jruby-9.1.5.0 }

env:
  - JRUBY_OPTS="--dev" DISPLAY=:99.0 LOGGER_LEVEL=WARN TRAVIS_NODE_VERSION="4"

before_script: "./script/front-end-test.sh"
